portrait: /images/portrait.png
og_image: /images/og-image.png
name: Andile Mbuyazwe
tagline: Graphic Designer
phone: +27 68 133 2294
email: ambuyazwe@gmail.com
linkedin: http://linkedin.com/in/andile-mbuyazwe
whatsapp: https://wa.me/27681332294
copyright: 2025

cta:
  heading: Digital Dreamweaver
  subheading: Transforming Concepts Into Reality